colorscheme base16
map global insert <tab> <space><space><space><space>
map global user i ": lsp-hover<ret>"

hook global WinCreate .* %{
    set-option global scrolloff 5,8
    set-option global tabstop 4
    set-option global aligntab false

    add-highlighter window/ number-lines -relative -hlcursor
}

set global ui_options ncurses_enable_mouse=0

eval %sh{kak-lsp --kakoune -s $kak_session}
hook global WinSetOption filetype=(rust|d|c|cpp|erlang) %{
    lsp-enable-window
}
