#!/bin/zsh
pgrep -x sxhkd >/dev/null || sxhkd &
xrandr --output $monitor --mode 1920x1080
xrandr --output $monitor --brightness 0.8

feh --bg-fill /home/etonit/Pictures/Shelter_Within_roly_poly_post.jpg

bspc rule -l
while [[ $? -ne 0 ]] do
    bspc rule -l
    sleep 0.1
done

bspc rule -r head
bspc rule -r tail
bspc rule -a .gscreenshot-wrapped state=floating

bspc config border_width  2
bspc config window_gap  3

bspc config top_padding  0
bspc config bottom_padding  0
bspc config left_padding  0
bspc config right_padding  0

bspc config split_ratio  0.5
bspc config gapless_monocle true
bspc monitor -d I II III IV V VI VII VIII IX X
urxvt &
